### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by NECOBLADE** [MC-Mods-Pete/ZombifiedPlayer#3]
Could you port this mod to 1.20.1?

**Comment by MC-Mods-Pete** [comment]
The mod currently uses the new 1.21 networking code, but I will have look how much effort it will be :)

**Comment by MC-Mods-Pete** [comment]
I just uploaded a backport to 1.20(.1) :)
https://modrinth.com/mod/zombified-player/version/0.9.3-1.20

**Comment by NECOBLADE** [comment]
Awesome! Thank you for the work you do!
