### ISSUE TITLE
0.9.3 for 1.20.1 - Zombies converted into Drowned lose their inventory

### ISSUE THREAD

**Issue by Jamma003** [MC-Mods-Pete/ZombifiedPlayer#4]
Just managed to lose all my gear by having the zombified player drown before I could kill him, he still carried the axe after becoming Drowned but on death only dropped one rotten flesh.

Id expect the drowned should also receive the inventory in this case?

**Comment by MC-Mods-Pete** [comment]
Thanks for the bug report, I will have a look

**Comment by MC-Mods-Pete** [comment]
I can confirm it's a bug, the Zombified Players should not convert at all. Will be fix in the next release

**Comment by MC-Mods-Pete** [comment]
fix released (in version 1.0.0), please reopen if there are still problems

**Comment by MC-Mods-Pete** [comment]
another short info: Zombified Players now "swim" / float on the water. They will not sink anymore.
